spring.application.name=demo

server.port=8085

spring.cloud.gateway.routes[0].id=Task6
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/a/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/a/(?<segment>.*), /hello/${segment}
